import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import './globals.css'

import "@/app/styles/main.css";
import {NextUIProvider} from "@nextui-org/react";

const inter = Roboto({weight: "400", subsets:['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${inter.className}`}>{<NextUIProvider>
        {children}
        </NextUIProvider>}</body>
    
    </html>
  );
}
